# Generated by Django 2.0.2 on 2018-05-14 21:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=70)),
                ('cal', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Component',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40)),
            ],
        ),
        migrations.CreateModel(
            name='CompProp',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.DecimalField(decimal_places=1, max_digits=5)),
                ('component', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='link_to_comp', to='mealtr.Component')),
            ],
        ),
        migrations.CreateModel(
            name='Day',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='DayActivity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mealtr.Activity')),
                ('day', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='link_to_daya', to='mealtr.Day')),
            ],
        ),
        migrations.CreateModel(
            name='DayMeal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.IntegerField(help_text='Please input in grams.')),
                ('day', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='link_to_daym', to='mealtr.Day')),
            ],
        ),
        migrations.CreateModel(
            name='FavActivity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mealtr.Activity')),
            ],
        ),
        migrations.CreateModel(
            name='FavMeal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Meal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40)),
                ('cal', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='MealComp',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.IntegerField(help_text='Please input in grams.')),
                ('component', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mealtr.Component')),
                ('meal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='link_to_meal', to='mealtr.Meal')),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sex', models.CharField(choices=[('F', 'Female'), ('M', 'Male'), ('I', 'Intersex')], max_length=10)),
                ('bd', models.DateField(help_text='Please use the following format: <em>YYYY-MM-DD</em>.')),
                ('height', models.DecimalField(decimal_places=2, help_text='Please input in metres.', max_digits=3)),
                ('weight', models.DecimalField(decimal_places=1, help_text='Please input in kilograms.', max_digits=4)),
                ('cal_goal', models.IntegerField(blank=True)),
                ('fav_activities', models.ManyToManyField(through='mealtr.FavActivity', to='mealtr.Activity')),
                ('fav_meals', models.ManyToManyField(through='mealtr.FavMeal', to='mealtr.Meal')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Property',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60)),
            ],
        ),
        migrations.AddField(
            model_name='meal',
            name='components',
            field=models.ManyToManyField(through='mealtr.MealComp', to='mealtr.Component'),
        ),
        migrations.AddField(
            model_name='favmeal',
            name='meal',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mealtr.Meal'),
        ),
        migrations.AddField(
            model_name='favmeal',
            name='profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='link_to_profm', to='mealtr.Profile'),
        ),
        migrations.AddField(
            model_name='favactivity',
            name='profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='link_to_profa', to='mealtr.Profile'),
        ),
        migrations.AddField(
            model_name='daymeal',
            name='meal',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mealtr.Meal'),
        ),
        migrations.AddField(
            model_name='day',
            name='activities',
            field=models.ManyToManyField(through='mealtr.DayActivity', to='mealtr.Activity'),
        ),
        migrations.AddField(
            model_name='day',
            name='meals',
            field=models.ManyToManyField(through='mealtr.DayMeal', to='mealtr.Meal'),
        ),
        migrations.AddField(
            model_name='day',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='compprop',
            name='prop',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='link_to_prop', to='mealtr.Property'),
        ),
        migrations.AddField(
            model_name='component',
            name='props',
            field=models.ManyToManyField(through='mealtr.CompProp', to='mealtr.Property'),
        ),
    ]
