# Generated by Django 2.0.2 on 2018-05-15 23:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mealtr', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activity',
            name='cal',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='component',
            name='props',
            field=models.ManyToManyField(null=True, through='mealtr.CompProp', to='mealtr.Property'),
        ),
        migrations.AlterField(
            model_name='day',
            name='activities',
            field=models.ManyToManyField(null=True, through='mealtr.DayActivity', to='mealtr.Activity'),
        ),
        migrations.AlterField(
            model_name='day',
            name='meals',
            field=models.ManyToManyField(null=True, through='mealtr.DayMeal', to='mealtr.Meal'),
        ),
        migrations.AlterField(
            model_name='meal',
            name='cal',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='meal',
            name='components',
            field=models.ManyToManyField(null=True, through='mealtr.MealComp', to='mealtr.Component'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='cal_goal',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='fav_activities',
            field=models.ManyToManyField(null=True, through='mealtr.FavActivity', to='mealtr.Activity'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='fav_meals',
            field=models.ManyToManyField(null=True, through='mealtr.FavMeal', to='mealtr.Meal'),
        ),
    ]
